# Generated by Django 5.1.1 on 2024-09-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeldRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birlestir', models.CharField(max_length=255, unique=True)),
                ('control_no', models.CharField(blank=True, max_length=100, null=True)),
                ('shop_field', models.CharField(blank=True, max_length=100)),
                ('weld_no', models.CharField(blank=True, max_length=100)),
                ('dia_inch', models.FloatField(blank=True, null=True)),
                ('dn', models.IntegerField(blank=True)),
                ('isometri_no', models.CharField(blank=True, max_length=100)),
                ('spool_no', models.CharField(blank=True, max_length=100)),
                ('revision', models.CharField(blank=True, max_length=50)),
                ('specs', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('weld_type', models.CharField(blank=True, max_length=100)),
                ('size_1', models.CharField(blank=True, max_length=50)),
                ('thick_1', models.FloatField(blank=True)),
                ('size_2', models.CharField(blank=True, max_length=50, null=True)),
                ('thick_2', models.FloatField(blank=True, null=True)),
                ('from_mat', models.CharField(blank=True, max_length=100, null=True)),
                ('to_mat', models.CharField(blank=True, max_length=100, null=True)),
                ('wps_no', models.CharField(blank=True, max_length=100, null=True)),
                ('from_desc_1', models.CharField(blank=True, max_length=100, null=True)),
                ('heat_no1', models.CharField(blank=True, max_length=100, null=True)),
                ('to_desc_2', models.CharField(blank=True, max_length=100, null=True)),
                ('heat_no2', models.CharField(blank=True, max_length=100, null=True)),
                ('fit_up_controlid', models.CharField(blank=True, max_length=100, null=True)),
                ('fitup_date', models.DateField(blank=True, null=True)),
                ('fit_result', models.CharField(blank=True, max_length=50, null=True)),
                ('welder_id', models.CharField(blank=True, max_length=100, null=True)),
                ('welder_2id', models.CharField(blank=True, max_length=100, null=True)),
                ('weld_date', models.DateField(blank=True, null=True)),
                ('weld_result', models.CharField(blank=True, max_length=100, null=True)),
                ('weld2', models.CharField(blank=True, max_length=100, null=True)),
                ('circ_seams_mt_pt', models.CharField(blank=True, max_length=100, null=True)),
                ('circ_seams_rt_ut', models.CharField(blank=True, max_length=100, null=True)),
                ('nozzle_welds_mt_pt', models.CharField(blank=True, max_length=100, null=True)),
                ('nozzle_welds_rt_ut', models.CharField(blank=True, max_length=100, null=True)),
                ('fillet_welds_mt_pt', models.CharField(blank=True, max_length=100, null=True)),
                ('mt_pt_date', models.DateField(blank=True, null=True)),
                ('mt_pt_result', models.CharField(blank=True, max_length=100, null=True)),
                ('mt_pt_reports', models.CharField(blank=True, max_length=100, null=True)),
                ('rt_ut_date', models.DateField(blank=True, null=True)),
                ('rt_ut_result', models.CharField(blank=True, max_length=100, null=True)),
                ('rt_ut_reports', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_system', models.CharField(blank=True, max_length=100, null=True)),
                ('description_area', models.CharField(blank=True, max_length=255, null=True)),
                ('total_length', models.FloatField(blank=True, null=True)),
                ('ped_cat', models.CharField(blank=True, max_length=50, null=True)),
                ('dn1', models.IntegerField(blank=True, null=True)),
                ('dn2', models.IntegerField(blank=True, null=True)),
                ('sheet_no', models.CharField(blank=True, max_length=50, null=True)),
                ('extra_welding_joint', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_responsible', models.CharField(blank=True, max_length=100, null=True)),
                ('test_package_no', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
