# Generated by Django 5.1.1 on 2024-09-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weldrecord',
            name='birlestir',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='weldrecord',
            name='dn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weldrecord',
            name='isometri_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='weldrecord',
            name='revision',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='weldrecord',
            name='shop_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='weldrecord',
            name='size_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='weldrecord',
            name='spool_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='weldrecord',
            name='thick_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weldrecord',
            name='weld_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='weldrecord',
            name='weld_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
