# Generated by Django 5.1.1 on 2024-10-02 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_weldrecord_birlestir_alter_weldrecord_dn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weldrecord',
            old_name='weld2',
            new_name='weld_process',
        ),
    ]
