# Generated by Django 5.1.1 on 2024-10-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_weld2_weldrecord_weld_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='weldrecord',
            name='Remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weldrecord',
            name='fitter_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weldrecord',
            name='fittup_checked_count',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
