# Generated by Django 5.1.1 on 2024-10-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_weldrecord_remarks_weldrecord_fitter_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weldrecord',
            old_name='Remarks',
            new_name='remarks',
        ),
        migrations.AlterField(
            model_name='weldrecord',
            name='fittup_checked_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
